### ISSUE TITLE
Would you consider relinquishing the crate name 'sequoia'

### ISSUE THREAD

**Issue by teythoon** [arpanlaha/sequoia#1]
Hi,

We noticed that you have registered the crate name `sequoia` on crates.io recently.  This is, unfortunately, very similar to the name of our PGP project https://sequoia-pgp.org/ and we have released crates with the `sequoia-` prefix for quite some time now.  We worry that (a) this may cause confusion for rustaceans, and (b) that this will prevent us from releasing a `sequoia` high-level crate as part of our ecosystem.

Would you consider changing the name of your octree implementation, and releasing the `sequoia` crate name to us on crates.io?

Thank you,
Justus for the Sequioa PGP community

**Comment by arpanlaha** [comment]
@teythoon sure thing, should I transfer it to you or another entity?

**Comment by teythoon** [comment]
Thank you for your understanding!  Yes, please transfer it to me, I'm `teythoon` on crates.io too (see https://crates.io/users/teythoon that displays my github username and shows that I also control the other `sequoia-` crates).

All the best for your project :)

**Comment by teythoon** [comment]
I completed the transfer.  I think I'm going to yank the existing crate, so that it is not added as dependency by mistake.  Have you picked a new name for your crate yet?  If so, I can link to the new crate if you wish.

Many thanks again!

**Comment by arpanlaha** [comment]
I haven't yet, but don't worry about linking to the new crate - it's still extremely early in development and I don't have a timeline of when it would be ready for actual use. Glad to help!
